version: "3.9"
services:
  db:
    platform: linux/amd64
    container_name: pg_db
    restart: always
    image: postgres:16.1
    volumes:
      - wellifiy_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
  web:
    platform: linux/amd64
    container_name: web_app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/wellifiy
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
volumes:
  wellifiy_data:
